In [13]:
%run -n speeach_recognizer.py -i data


In [21]:
X = np.array([])
y = []
warnings.filterwarnings('ignore')

for dirname in os.listdir(input_folder):
    subfolder = os.path.join(input_folder, dirname)

    if not os.path.isdir(subfolder):
        continue

    label = subfolder[subfolder.rfind('/') + 1:]
    for filename in [x for x in os.listdir(subfolder) if x.endswith('.wav')][:-1]:
        filepath = os.path.join(subfolder, filename)
        sampling_freq, audio = wavfile.read(filepath)

        mfcc_features = mfcc(audio, sampling_freq)
        if len(X) == 0:
            X = mfcc_features
        else:
            X = np.append(X, mfcc_features, axis=0)
        y.append(label)

    # Each model builds for each class
    hmm_trainer = HMMTrainer()
    print('Train', label, 'X shape', X.shape)
    hmm_trainer.train(X)
    hmm_models.append((hmm_trainer, label))
    hmm_trainer = None

Train apple X shape (558, 13)
Train banana X shape (1262, 13)
Train kiwi X shape (1811, 13)
Train lime X shape (2413, 13)
Train orange X shape (3488, 13)
Train peach X shape (4398, 13)
Train pineapple X shape (5195, 13)


In [24]:
for trainer, label in hmm_models:
    print("label", label)
    print("============")
    model = trainer.model
    print("Transition matrix")
    print(model.transmat_)

    print("Means and vars of each hidden state")
    for i in range(model.n_components):
        print("{0}th hidden state".format(i))
        print("mean = ", model.means_[i])
        print("var = ", np.diag(model.covars_[i]))

label apple
Transition matrix
[[  8.90121907e-01   1.57811345e-36   4.00369695e-09   1.09878089e-01]
 [  1.77312419e-64   9.06307298e-01   9.26744825e-56   9.36927016e-02]
 [  6.97941641e-02   4.10994861e-65   8.98417525e-01   3.17883107e-02]
 [  3.06282988e-02   1.00824629e-01   9.38508327e-02   7.74696240e-01]]
Means and vars of each hidden state
0th hidden state
mean =  [ 16.73073046 -11.76530251 -36.90453229   2.81417331  -2.15661843
  10.17068614 -17.30243072   0.45776959 -16.93755906  13.04499504
  10.31106187 -22.16985101  -0.59571075]
var =  [  0.55576738  17.7879826   29.64925554  29.53209561  41.32306071
  71.61295158  42.72282627  39.5284297   65.86065214  58.00296727
  50.04505045  46.23314045  51.77421655]
1th hidden state
mean =  [ 17.78780147  10.49398059 -20.67178941 -27.71242097 -29.76004065
  -3.01899888   2.19153251  12.75463134  -1.07557474  11.76858632
   1.99171767 -18.24299976  -6.60442485]
var =  [  1.15994064  28.05858095  28.88015523  53.4405346   40.07986784


Transition matrix
[[  9.09417890e-001   3.08609229e-003   8.74960180e-002   5.15644506e-114]
 [  1.90155212e-002   9.23349861e-001   2.31056583e-002   3.45289595e-002]
 [  1.46941931e-001   1.54534519e-002   8.17689020e-001   1.99155969e-002]
 [  3.95660270e-115   5.48640698e-002   6.30927341e-044   9.45135930e-001]]
Means and vars of each hidden state
0th hidden state
mean =  [ 17.73362983   6.54168685 -34.01473788 -32.21960308  -4.53226667
   4.06425775 -18.36309896  14.62994859 -13.42644017   1.9563942
  -3.65040493   1.18955864  -7.23589214]
var =  [   1.64655342   33.31535746   35.63663636   58.40679644   54.32469403
   99.38113528   71.24155931   65.89238433  112.34743294  114.02068311
   96.07711204   32.58802627   65.85905187]
1th hidden state
mean =  [ 17.05275117   4.21946789 -20.98884907 -24.72758376 -27.08046501
  -3.59498036   1.29650474   9.24400026  -1.96004026   9.87471185
   0.37659999 -15.11556245  -6.87262762]
var =  [  2.71223179  96.09349456  40.95835989  73.941199